// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The AddressRelationships. </summary>
    internal partial class AddressRelationships
    {
        /// <summary> Initializes a new instance of AddressRelationships. </summary>
        internal AddressRelationships()
        {
        }

        public RelationshipsMultipleDocument AddressDetails { get; }
    }
}
