// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The AddressesDocumentLinks. </summary>
    public partial class AddressesDocumentLinks : TopLevelLinks
    {
        /// <summary> Initializes a new instance of AddressesDocumentLinks. </summary>
        internal AddressesDocumentLinks()
        {
        }

        /// <summary> Initializes a new instance of AddressesDocumentLinks. </summary>
        /// <param name="self"></param>
        /// <param name="related"></param>
        /// <param name="describedBy"></param>
        /// <param name="first"></param>
        /// <param name="last"></param>
        /// <param name="prev"></param>
        /// <param name="next"></param>
        internal AddressesDocumentLinks(string self, string related, string describedBy, string first, string last, string prev, string next) : base(self, related, describedBy, first, last, prev, next)
        {
        }
    }
}
