// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace MyCrmSampleClient.MyCrmApi.Models
{
    public partial class AdviserRelationshipsAddresses : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Data != null)
            {
                writer.WritePropertyName("data");
                writer.WriteStartArray();
                foreach (var item in Data)
                {
                    writer.WriteObjectValue(item);
                }
                writer.WriteEndArray();
            }
            else
            {
                writer.WriteNull("data");
            }
            writer.WriteEndObject();
        }

        internal static AdviserRelationshipsAddresses DeserializeAdviserRelationshipsAddresses(JsonElement element)
        {
            Optional<RelationshipsMultipleDocumentLinks> links = default;
            Optional<IReadOnlyDictionary<string, object>> meta = default;
            IList<ResourceIdentifier> data = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("links"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    links = RelationshipsMultipleDocumentLinks.DeserializeRelationshipsMultipleDocumentLinks(property.Value);
                    continue;
                }
                if (property.NameEquals("meta"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    Dictionary<string, object> dictionary = new Dictionary<string, object>();
                    foreach (var property0 in property.Value.EnumerateObject())
                    {
                        dictionary.Add(property0.Name, property0.Value.GetObject());
                    }
                    meta = dictionary;
                    continue;
                }
                if (property.NameEquals("data"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        data = null;
                        continue;
                    }
                    List<ResourceIdentifier> array = new List<ResourceIdentifier>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(ResourceIdentifier.DeserializeResourceIdentifier(item));
                    }
                    data = array;
                    continue;
                }
            }
            return new AdviserRelationshipsAddresses(links.Value, Optional.ToDictionary(meta), data);
        }
    }
}
