// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Azure.Core;

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The AdviserDetail. </summary>
    internal partial class AdviserDetail
    {
        /// <summary> Initializes a new instance of AdviserDetail. </summary>
        /// <param name="type"></param>
        /// <param name="id"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="type"/> or <paramref name="id"/> is null. </exception>
        internal AdviserDetail(string type, string id)
        {
            if (type == null)
            {
                throw new ArgumentNullException(nameof(type));
            }
            if (id == null)
            {
                throw new ArgumentNullException(nameof(id));
            }

            Type = type;
            Id = id;
            Meta = new ChangeTrackingDictionary<string, object>();
        }

        public string Type { get; }
        public string Id { get; }
        public AdviserDetailAttributes Attributes { get; }
        public AdviserDetailRelationships Relationships { get; }
        public AdviserDetailLinks Links { get; }
        /// <summary> Dictionary of &lt;any&gt;. </summary>
        public IReadOnlyDictionary<string, object> Meta { get; }
    }
}
