// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The AdviserRelationships. </summary>
    public partial class AdviserRelationships
    {
        /// <summary> Initializes a new instance of AdviserRelationships. </summary>
        public AdviserRelationships()
        {
        }

        /// <summary> Initializes a new instance of AdviserRelationships. </summary>
        /// <param name="adviserDetails"></param>
        /// <param name="contactGroups"></param>
        internal AdviserRelationships(RelationshipsSingleDocument adviserDetails, RelationshipsMultipleDocument contactGroups)
        {
            AdviserDetails = adviserDetails;
            ContactGroups = contactGroups;
        }

        public RelationshipsSingleDocument AdviserDetails { get; set; }
        public RelationshipsMultipleDocument ContactGroups { get; set; }
    }
}
