// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using Azure.Core;

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The AdviserAddress. </summary>
    public partial class AdviserAddress : IncludedResource
    {
        /// <summary> Initializes a new instance of AdviserAddress. </summary>
        public AdviserAddress()
        {
            Meta = new ChangeTrackingDictionary<string, object>();
            Type = "adviser-address";
        }

        /// <summary> Initializes a new instance of AdviserAddress. </summary>
        /// <param name="type"></param>
        /// <param name="id"></param>
        /// <param name="attributes"></param>
        /// <param name="relationships"></param>
        /// <param name="links"></param>
        /// <param name="meta"> Dictionary of &lt;any&gt;. </param>
        internal AdviserAddress(string type, string id, AdviserAddressAttributes attributes, AdviserAddressRelationships relationships, AdviserAddressLinks links, IReadOnlyDictionary<string, object> meta) : base(type, id)
        {
            Attributes = attributes;
            Relationships = relationships;
            Links = links;
            Meta = meta;
            Type = type ?? "adviser-address";
        }

        /// <summary> Gets or sets the attributes. </summary>
        public AdviserAddressAttributes Attributes { get; set; }
        /// <summary> Gets or sets the relationships. </summary>
        public AdviserAddressRelationships Relationships { get; set; }
        /// <summary> Gets the links. </summary>
        public AdviserAddressLinks Links { get; }
        /// <summary> Dictionary of &lt;any&gt;. </summary>
        public IReadOnlyDictionary<string, object> Meta { get; }
    }
}
