// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace MyCrmSampleClient.MyCrmApi.Models
{
    public partial class AgreementHolderRelationships : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsDefined(ApiFamilyFranchisees))
            {
                writer.WritePropertyName("apiFamilyFranchisees");
                writer.WriteObjectValue(ApiFamilyFranchisees);
            }
            if (Optional.IsDefined(Organisation))
            {
                writer.WritePropertyName("organisation");
                writer.WriteObjectValue(Organisation);
            }
            writer.WriteEndObject();
        }

        internal static AgreementHolderRelationships DeserializeAgreementHolderRelationships(JsonElement element)
        {
            Optional<RelationshipsMultipleDocument> apiFamilyFranchisees = default;
            Optional<AgreementHolderRelationshipsOrganisation> organisation = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("apiFamilyFranchisees"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    apiFamilyFranchisees = RelationshipsMultipleDocument.DeserializeRelationshipsMultipleDocument(property.Value);
                    continue;
                }
                if (property.NameEquals("organisation"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    organisation = AgreementHolderRelationshipsOrganisation.DeserializeAgreementHolderRelationshipsOrganisation(property.Value);
                    continue;
                }
            }
            return new AgreementHolderRelationships(apiFamilyFranchisees.Value, organisation.Value);
        }
    }
}
