// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Azure.Core;

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The ApiLoanSecurity. </summary>
    internal partial class ApiLoanSecurity
    {
        /// <summary> Initializes a new instance of ApiLoanSecurity. </summary>
        /// <param name="id"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="id"/> is null. </exception>
        internal ApiLoanSecurity(string id)
        {
            if (id == null)
            {
                throw new ArgumentNullException(nameof(id));
            }

            Id = id;
            LoanSecurityInfo = new ChangeTrackingList<DealSecurity>();
        }

        /// <summary> Gets the id. </summary>
        public string Id { get; }
        /// <summary> Gets the loan security info. </summary>
        public IReadOnlyList<DealSecurity> LoanSecurityInfo { get; }
    }
}
