// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The AssetSubTypeLinks. </summary>
    public partial class AssetSubTypeLinks : ResourceLinks
    {
        /// <summary> Initializes a new instance of AssetSubTypeLinks. </summary>
        internal AssetSubTypeLinks()
        {
        }

        /// <summary> Initializes a new instance of AssetSubTypeLinks. </summary>
        /// <param name="self"></param>
        internal AssetSubTypeLinks(string self) : base(self)
        {
        }
    }
}
