// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using Azure.Core;

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The Business. </summary>
    public partial class Business : IncludedResource
    {
        /// <summary> Initializes a new instance of Business. </summary>
        public Business()
        {
            Meta = new ChangeTrackingDictionary<string, object>();
            Type = "business";
        }

        /// <summary> Initializes a new instance of Business. </summary>
        /// <param name="type"></param>
        /// <param name="id"></param>
        /// <param name="attributes"></param>
        /// <param name="relationships"></param>
        /// <param name="links"></param>
        /// <param name="meta"> Dictionary of &lt;any&gt;. </param>
        internal Business(string type, string id, BusinessAttributes attributes, BusinessRelationships relationships, BusinessLinks links, IReadOnlyDictionary<string, object> meta) : base(type, id)
        {
            Attributes = attributes;
            Relationships = relationships;
            Links = links;
            Meta = meta;
            Type = type ?? "business";
        }

        /// <summary> Gets or sets the attributes. </summary>
        public BusinessAttributes Attributes { get; set; }
        /// <summary> Gets or sets the relationships. </summary>
        public BusinessRelationships Relationships { get; set; }
        /// <summary> Gets the links. </summary>
        public BusinessLinks Links { get; }
        /// <summary> Dictionary of &lt;any&gt;. </summary>
        public IReadOnlyDictionary<string, object> Meta { get; }
    }
}
