// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The ContactsType. </summary>
    public readonly partial struct ContactsType : IEquatable<ContactsType>
    {
        private readonly string _value;

        /// <summary> Determines if two <see cref="ContactsType"/> values are the same. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public ContactsType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string ContactsValue = "contacts";

        /// <summary> contacts. </summary>
        public static ContactsType Contacts { get; } = new ContactsType(ContactsValue);
        /// <summary> Determines if two <see cref="ContactsType"/> values are the same. </summary>
        public static bool operator ==(ContactsType left, ContactsType right) => left.Equals(right);
        /// <summary> Determines if two <see cref="ContactsType"/> values are not the same. </summary>
        public static bool operator !=(ContactsType left, ContactsType right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="ContactsType"/>. </summary>
        public static implicit operator ContactsType(string value) => new ContactsType(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is ContactsType other && Equals(other);
        /// <inheritdoc />
        public bool Equals(ContactsType other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
