// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The ContactsEntityType. </summary>
    public readonly partial struct ContactsEntityType : IEquatable<ContactsEntityType>
    {
        private readonly string _value;

        /// <summary> Initializes a new instance of <see cref="ContactsEntityType"/>. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public ContactsEntityType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string ContactsValue = "contacts";

        /// <summary> contacts. </summary>
        public static ContactsEntityType Contacts { get; } = new ContactsEntityType(ContactsValue);
        /// <summary> Determines if two <see cref="ContactsEntityType"/> values are the same. </summary>
        public static bool operator ==(ContactsEntityType left, ContactsEntityType right) => left.Equals(right);
        /// <summary> Determines if two <see cref="ContactsEntityType"/> values are not the same. </summary>
        public static bool operator !=(ContactsEntityType left, ContactsEntityType right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="ContactsEntityType"/>. </summary>
        public static implicit operator ContactsEntityType(string value) => new ContactsEntityType(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is ContactsEntityType other && Equals(other);
        /// <inheritdoc />
        public bool Equals(ContactsEntityType other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
