// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The ContactAddressesType. </summary>
    public readonly partial struct ContactAddressesType : IEquatable<ContactAddressesType>
    {
        private readonly string _value;

        /// <summary> Determines if two <see cref="ContactAddressesType"/> values are the same. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public ContactAddressesType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string ContactAddressValue = "contact-address";

        /// <summary> contact-address. </summary>
        public static ContactAddressesType ContactAddress { get; } = new ContactAddressesType(ContactAddressValue);
        /// <summary> Determines if two <see cref="ContactAddressesType"/> values are the same. </summary>
        public static bool operator ==(ContactAddressesType left, ContactAddressesType right) => left.Equals(right);
        /// <summary> Determines if two <see cref="ContactAddressesType"/> values are not the same. </summary>
        public static bool operator !=(ContactAddressesType left, ContactAddressesType right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="ContactAddressesType"/>. </summary>
        public static implicit operator ContactAddressesType(string value) => new ContactAddressesType(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is ContactAddressesType other && Equals(other);
        /// <inheritdoc />
        public bool Equals(ContactAddressesType other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
