// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The ContactGroupLinks. </summary>
    public partial class ContactGroupLinks : ResourceLinks
    {
        /// <summary> Initializes a new instance of ContactGroupLinks. </summary>
        internal ContactGroupLinks()
        {
        }

        /// <summary> Initializes a new instance of ContactGroupLinks. </summary>
        /// <param name="self"></param>
        internal ContactGroupLinks(string self) : base(self)
        {
        }
    }
}
