// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The ContactExternalReferenceRelationships. </summary>
    public partial class ContactExternalReferenceRelationships
    {
        /// <summary> Initializes a new instance of ContactExternalReferenceRelationships. </summary>
        public ContactExternalReferenceRelationships()
        {
        }

        /// <summary> Initializes a new instance of ContactExternalReferenceRelationships. </summary>
        /// <param name="integration"></param>
        /// <param name="contact"></param>
        internal ContactExternalReferenceRelationships(RelationshipsSingleDocument integration, RelationshipsSingleDocument contact)
        {
            Integration = integration;
            Contact = contact;
        }

        /// <summary> Gets or sets the integration. </summary>
        public RelationshipsSingleDocument Integration { get; set; }
        /// <summary> Gets or sets the contact. </summary>
        public RelationshipsSingleDocument Contact { get; set; }
    }
}
