// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The ContactGroupRelationships. </summary>
    public partial class ContactGroupRelationships
    {
        /// <summary> Initializes a new instance of ContactGroupRelationships. </summary>
        public ContactGroupRelationships()
        {
        }

        /// <summary> Initializes a new instance of ContactGroupRelationships. </summary>
        /// <param name="contacts"></param>
        internal ContactGroupRelationships(RelationshipsMultipleDocument contacts)
        {
            Contacts = contacts;
        }

        public RelationshipsMultipleDocument Contacts { get; set; }
    }
}
