// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The ContactAddressDetailAttributes. </summary>
    internal partial class ContactAddressDetailAttributes
    {
        /// <summary> Initializes a new instance of ContactAddressDetailAttributes. </summary>
        internal ContactAddressDetailAttributes()
        {
        }

        public DateTimeOffset? Created { get; }
        public DateTimeOffset? Updated { get; }
    }
}
