// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace MyCrmSampleClient.MyCrmApi.Models
{
    public partial class ContactRelationships : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsDefined(ContactGroup))
            {
                writer.WritePropertyName("contactGroup");
                writer.WriteObjectValue(ContactGroup);
            }
            if (Optional.IsDefined(Ownership))
            {
                writer.WritePropertyName("ownership");
                writer.WriteObjectValue(Ownership);
            }
            if (Optional.IsDefined(ExternalReferences))
            {
                writer.WritePropertyName("externalReferences");
                writer.WriteObjectValue(ExternalReferences);
            }
            if (Optional.IsDefined(Deals))
            {
                writer.WritePropertyName("deals");
                writer.WriteObjectValue(Deals);
            }
            if (Optional.IsDefined(Employments))
            {
                writer.WritePropertyName("employments");
                writer.WriteObjectValue(Employments);
            }
            if (Optional.IsDefined(ContactAddress))
            {
                writer.WritePropertyName("contactAddress");
                writer.WriteObjectValue(ContactAddress);
            }
            writer.WriteEndObject();
        }

        internal static ContactRelationships DeserializeContactRelationships(JsonElement element)
        {
            Optional<RelationshipsSingleDocument> contactGroup = default;
            Optional<RelationshipsMultipleDocument> ownership = default;
            Optional<RelationshipsMultipleDocument> externalReferences = default;
            Optional<RelationshipsMultipleDocument> deals = default;
            Optional<ContactRelationshipsEmployments> employments = default;
            Optional<ContactRelationshipsContactAddress> contactAddress = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("contactGroup"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    contactGroup = RelationshipsSingleDocument.DeserializeRelationshipsSingleDocument(property.Value);
                    continue;
                }
                if (property.NameEquals("ownership"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    ownership = RelationshipsMultipleDocument.DeserializeRelationshipsMultipleDocument(property.Value);
                    continue;
                }
                if (property.NameEquals("externalReferences"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    externalReferences = RelationshipsMultipleDocument.DeserializeRelationshipsMultipleDocument(property.Value);
                    continue;
                }
                if (property.NameEquals("deals"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    deals = RelationshipsMultipleDocument.DeserializeRelationshipsMultipleDocument(property.Value);
                    continue;
                }
                if (property.NameEquals("employments"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    employments = ContactRelationshipsEmployments.DeserializeContactRelationshipsEmployments(property.Value);
                    continue;
                }
                if (property.NameEquals("contactAddress"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    contactAddress = ContactRelationshipsContactAddress.DeserializeContactRelationshipsContactAddress(property.Value);
                    continue;
                }
            }
            return new ContactRelationships(contactGroup.Value, ownership.Value, externalReferences.Value, deals.Value, employments.Value, contactAddress.Value);
        }
    }
}
