// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The DealStructuresType. </summary>
    internal readonly partial struct DealStructuresType : IEquatable<DealStructuresType>
    {
        private readonly string _value;

        /// <summary> Determines if two <see cref="DealStructuresType"/> values are the same. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public DealStructuresType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string DealStructuresValue = "deal-structures";

        /// <summary> deal-structures. </summary>
        public static DealStructuresType DealStructures { get; } = new DealStructuresType(DealStructuresValue);
        /// <summary> Determines if two <see cref="DealStructuresType"/> values are the same. </summary>
        public static bool operator ==(DealStructuresType left, DealStructuresType right) => left.Equals(right);
        /// <summary> Determines if two <see cref="DealStructuresType"/> values are not the same. </summary>
        public static bool operator !=(DealStructuresType left, DealStructuresType right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="DealStructuresType"/>. </summary>
        public static implicit operator DealStructuresType(string value) => new DealStructuresType(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is DealStructuresType other && Equals(other);
        /// <inheritdoc />
        public bool Equals(DealStructuresType other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
