// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Text.Json;
using Azure.Core;

namespace MyCrmSampleClient.MyCrmApi.Models
{
    public partial class DealImportantDateAttributes : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            writer.WriteEndObject();
        }

        internal static DealImportantDateAttributes DeserializeDealImportantDateAttributes(JsonElement element)
        {
            Optional<DateTimeOffset?> date = default;
            Optional<DealImportantDateAttributesDateType> dateType = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("date"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        date = null;
                        continue;
                    }
                    date = property.Value.GetDateTimeOffset("D");
                    continue;
                }
                if (property.NameEquals("dateType"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    dateType = new DealImportantDateAttributesDateType(property.Value.GetString());
                    continue;
                }
            }
            return new DealImportantDateAttributes(Optional.ToNullable(date), Optional.ToNullable(dateType));
        }
    }
}
