// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Azure.Core;

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The DealStructureImportantDate. </summary>
    internal partial class DealStructureImportantDate
    {
        /// <summary> Initializes a new instance of DealStructureImportantDate. </summary>
        /// <param name="type"></param>
        /// <param name="id"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="id"/> is null. </exception>
        internal DealStructureImportantDate(DealStructureImportantDatesType type, string id)
        {
            if (id == null)
            {
                throw new ArgumentNullException(nameof(id));
            }

            Type = type;
            Id = id;
            Meta = new ChangeTrackingDictionary<string, object>();
        }

        public DealStructureImportantDatesType Type { get; }
        public string Id { get; }
        public DealStructureImportantDateAttributes Attributes { get; }
        public DealStructureImportantDateRelationships Relationships { get; }
        public DealStructureImportantDateLinks Links { get; }
        /// <summary> Dictionary of &lt;any&gt;. </summary>
        public IReadOnlyDictionary<string, object> Meta { get; }
    }
}
