// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Text.Json;
using Azure.Core;

namespace MyCrmSampleClient.MyCrmApi.Models
{
    public partial class DealImportantDateAttributes : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsDefined(Date))
            {
                if (Date != null)
                {
                    writer.WritePropertyName("date");
                    writer.WriteStringValue(Date.Value, "O");
                }
                else
                {
                    writer.WriteNull("date");
                }
            }
            writer.WriteEndObject();
        }

        internal static DealImportantDateAttributes DeserializeDealImportantDateAttributes(JsonElement element)
        {
            Optional<DateTimeOffset?> date = default;
            Optional<string> dateTypeDesc = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("date"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        date = null;
                        continue;
                    }
                    date = property.Value.GetDateTimeOffset("O");
                    continue;
                }
                if (property.NameEquals("dateTypeDesc"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        dateTypeDesc = null;
                        continue;
                    }
                    dateTypeDesc = property.Value.GetString();
                    continue;
                }
            }
            return new DealImportantDateAttributes(Optional.ToNullable(date), dateTypeDesc.Value);
        }
    }
}
