// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using Azure.Core;

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The Deal. </summary>
    public partial class Deal : IncludedResource
    {
        /// <summary> Initializes a new instance of Deal. </summary>
        public Deal()
        {
            Meta = new ChangeTrackingDictionary<string, object>();
            Type = "deals";
        }

        /// <summary> Initializes a new instance of Deal. </summary>
        /// <param name="type"></param>
        /// <param name="id"></param>
        /// <param name="attributes"></param>
        /// <param name="relationships"></param>
        /// <param name="links"></param>
        /// <param name="meta"> Dictionary of &lt;any&gt;. </param>
        internal Deal(string type, string id, DealAttributes attributes, DealRelationships relationships, DealLinks links, IReadOnlyDictionary<string, object> meta) : base(type, id)
        {
            Attributes = attributes;
            Relationships = relationships;
            Links = links;
            Meta = meta;
            Type = type ?? "deals";
        }

        public DealAttributes Attributes { get; set; }
        public DealRelationships Relationships { get; set; }
        public DealLinks Links { get; }
        /// <summary> Dictionary of &lt;any&gt;. </summary>
        public IReadOnlyDictionary<string, object> Meta { get; }
    }
}
