// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The DealParticipantLinks. </summary>
    public partial class DealParticipantLinks : ResourceLinks
    {
        /// <summary> Initializes a new instance of DealParticipantLinks. </summary>
        internal DealParticipantLinks()
        {
        }

        /// <summary> Initializes a new instance of DealParticipantLinks. </summary>
        /// <param name="self"></param>
        internal DealParticipantLinks(string self) : base(self)
        {
        }
    }
}
