// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The DealAttributesDealStatus. </summary>
    public readonly partial struct DealAttributesDealStatus : IEquatable<DealAttributesDealStatus>
    {
        private readonly string _value;

        /// <summary> Initializes a new instance of <see cref="DealAttributesDealStatus"/>. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public DealAttributesDealStatus(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string NewLeadsValue = "NewLeads";
        private const string ResearchingValue = "Researching";
        private const string PreApprovedValue = "PreApproved";
        private const string ConditionallyApprovedValue = "ConditionallyApproved";
        private const string UnconditionallyApprovedValue = "UnconditionallyApproved";
        private const string LodgedValue = "Lodged";
        private const string InProgressValue = "InProgress";
        private const string PendingSettlementValue = "PendingSettlement";
        private const string VariedValue = "Varied";
        private const string RepaidValue = "Repaid";
        private const string WithdrawnValue = "Withdrawn";
        private const string CancelledValue = "Cancelled";
        private const string SettledValue = "Settled";

        /// <summary> NewLeads. </summary>
        public static DealAttributesDealStatus NewLeads { get; } = new DealAttributesDealStatus(NewLeadsValue);
        /// <summary> Researching. </summary>
        public static DealAttributesDealStatus Researching { get; } = new DealAttributesDealStatus(ResearchingValue);
        /// <summary> PreApproved. </summary>
        public static DealAttributesDealStatus PreApproved { get; } = new DealAttributesDealStatus(PreApprovedValue);
        /// <summary> ConditionallyApproved. </summary>
        public static DealAttributesDealStatus ConditionallyApproved { get; } = new DealAttributesDealStatus(ConditionallyApprovedValue);
        /// <summary> UnconditionallyApproved. </summary>
        public static DealAttributesDealStatus UnconditionallyApproved { get; } = new DealAttributesDealStatus(UnconditionallyApprovedValue);
        /// <summary> Lodged. </summary>
        public static DealAttributesDealStatus Lodged { get; } = new DealAttributesDealStatus(LodgedValue);
        /// <summary> InProgress. </summary>
        public static DealAttributesDealStatus InProgress { get; } = new DealAttributesDealStatus(InProgressValue);
        /// <summary> PendingSettlement. </summary>
        public static DealAttributesDealStatus PendingSettlement { get; } = new DealAttributesDealStatus(PendingSettlementValue);
        /// <summary> Varied. </summary>
        public static DealAttributesDealStatus Varied { get; } = new DealAttributesDealStatus(VariedValue);
        /// <summary> Repaid. </summary>
        public static DealAttributesDealStatus Repaid { get; } = new DealAttributesDealStatus(RepaidValue);
        /// <summary> Withdrawn. </summary>
        public static DealAttributesDealStatus Withdrawn { get; } = new DealAttributesDealStatus(WithdrawnValue);
        /// <summary> Cancelled. </summary>
        public static DealAttributesDealStatus Cancelled { get; } = new DealAttributesDealStatus(CancelledValue);
        /// <summary> Settled. </summary>
        public static DealAttributesDealStatus Settled { get; } = new DealAttributesDealStatus(SettledValue);
        /// <summary> Determines if two <see cref="DealAttributesDealStatus"/> values are the same. </summary>
        public static bool operator ==(DealAttributesDealStatus left, DealAttributesDealStatus right) => left.Equals(right);
        /// <summary> Determines if two <see cref="DealAttributesDealStatus"/> values are not the same. </summary>
        public static bool operator !=(DealAttributesDealStatus left, DealAttributesDealStatus right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="DealAttributesDealStatus"/>. </summary>
        public static implicit operator DealAttributesDealStatus(string value) => new DealAttributesDealStatus(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is DealAttributesDealStatus other && Equals(other);
        /// <inheritdoc />
        public bool Equals(DealAttributesDealStatus other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
