// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The DealRelationships. </summary>
    public partial class DealRelationships
    {
        /// <summary> Initializes a new instance of DealRelationships. </summary>
        public DealRelationships()
        {
        }

        /// <summary> Initializes a new instance of DealRelationships. </summary>
        /// <param name="dealScenario"></param>
        /// <param name="participants"></param>
        /// <param name="externalReferences"></param>
        /// <param name="dealStructures"></param>
        /// <param name="contacts"></param>
        /// <param name="importantDates"></param>
        /// <param name="adviser"></param>
        /// <param name="dealNotes"></param>
        internal DealRelationships(RelationshipsSingleDocument dealScenario, RelationshipsMultipleDocument participants, RelationshipsMultipleDocument externalReferences, RelationshipsMultipleDocument dealStructures, DealRelationshipsContacts contacts, RelationshipsMultipleDocument importantDates, RelationshipsSingleDocument adviser, RelationshipsMultipleDocument dealNotes)
        {
            DealScenario = dealScenario;
            Participants = participants;
            ExternalReferences = externalReferences;
            DealStructures = dealStructures;
            Contacts = contacts;
            ImportantDates = importantDates;
            Adviser = adviser;
            DealNotes = dealNotes;
        }

        public RelationshipsSingleDocument DealScenario { get; set; }
        public RelationshipsMultipleDocument Participants { get; set; }
        public RelationshipsMultipleDocument ExternalReferences { get; set; }
        public RelationshipsMultipleDocument DealStructures { get; set; }
        public DealRelationshipsContacts Contacts { get; set; }
        public RelationshipsMultipleDocument ImportantDates { get; set; }
        public RelationshipsSingleDocument Adviser { get; set; }
        public RelationshipsMultipleDocument DealNotes { get; set; }
    }
}
