// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace MyCrmSampleClient.MyCrmApi.Models
{
    public partial class EnquirySourceAttributes : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            writer.WriteEndObject();
        }

        internal static EnquirySourceAttributes DeserializeEnquirySourceAttributes(JsonElement element)
        {
            Optional<int> sourceCategoryId = default;
            Optional<string> sourceCategoryName = default;
            Optional<int> sourceId = default;
            Optional<string> sourceName = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("sourceCategoryId"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    sourceCategoryId = property.Value.GetInt32();
                    continue;
                }
                if (property.NameEquals("sourceCategoryName"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        sourceCategoryName = null;
                        continue;
                    }
                    sourceCategoryName = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("sourceId"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    sourceId = property.Value.GetInt32();
                    continue;
                }
                if (property.NameEquals("sourceName"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        sourceName = null;
                        continue;
                    }
                    sourceName = property.Value.GetString();
                    continue;
                }
            }
            return new EnquirySourceAttributes(Optional.ToNullable(sourceCategoryId), sourceCategoryName.Value, Optional.ToNullable(sourceId), sourceName.Value);
        }
    }
}
