// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using Azure.Core;

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The ErrorMeta. </summary>
    internal partial class ErrorMeta
    {
        /// <summary> Initializes a new instance of ErrorMeta. </summary>
        internal ErrorMeta()
        {
            Data = new ChangeTrackingDictionary<string, object>();
        }

        /// <summary> Initializes a new instance of ErrorMeta. </summary>
        /// <param name="data"> Dictionary of &lt;any&gt;. </param>
        internal ErrorMeta(IReadOnlyDictionary<string, object> data)
        {
            Data = data;
        }

        /// <summary> Dictionary of &lt;any&gt;. </summary>
        public IReadOnlyDictionary<string, object> Data { get; }
    }
}
