// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The ExpenseLinks. </summary>
    public partial class ExpenseLinks : ResourceLinks
    {
        /// <summary> Initializes a new instance of ExpenseLinks. </summary>
        internal ExpenseLinks()
        {
        }

        /// <summary> Initializes a new instance of ExpenseLinks. </summary>
        /// <param name="self"></param>
        internal ExpenseLinks(string self) : base(self)
        {
        }
    }
}
