// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The FinancialRelationships. </summary>
    public partial class FinancialRelationships
    {
        /// <summary> Initializes a new instance of FinancialRelationships. </summary>
        public FinancialRelationships()
        {
        }

        /// <summary> Initializes a new instance of FinancialRelationships. </summary>
        /// <param name="expenses"></param>
        /// <param name="addresses"></param>
        /// <param name="clients"></param>
        /// <param name="incomes"></param>
        /// <param name="liabilities"></param>
        /// <param name="assets"></param>
        internal FinancialRelationships(RelationshipsMultipleDocument expenses, RelationshipsMultipleDocument addresses, RelationshipsMultipleDocument clients, RelationshipsMultipleDocument incomes, RelationshipsMultipleDocument liabilities, RelationshipsMultipleDocument assets)
        {
            Expenses = expenses;
            Addresses = addresses;
            Clients = clients;
            Incomes = incomes;
            Liabilities = liabilities;
            Assets = assets;
        }

        /// <summary> Gets or sets the expenses. </summary>
        public RelationshipsMultipleDocument Expenses { get; set; }
        /// <summary> Gets or sets the addresses. </summary>
        public RelationshipsMultipleDocument Addresses { get; set; }
        /// <summary> Gets or sets the clients. </summary>
        public RelationshipsMultipleDocument Clients { get; set; }
        /// <summary> Gets or sets the incomes. </summary>
        public RelationshipsMultipleDocument Incomes { get; set; }
        /// <summary> Gets or sets the liabilities. </summary>
        public RelationshipsMultipleDocument Liabilities { get; set; }
        /// <summary> Gets or sets the assets. </summary>
        public RelationshipsMultipleDocument Assets { get; set; }
    }
}
