// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Text.Json;
using Azure.Core;

namespace MyCrmSampleClient.MyCrmApi.Models
{
    public partial class IncomeAttributes : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsDefined(Description))
            {
                if (Description != null)
                {
                    writer.WritePropertyName("description");
                    writer.WriteStringValue(Description);
                }
                else
                {
                    writer.WriteNull("description");
                }
            }
            if (Optional.IsDefined(Value))
            {
                if (Value != null)
                {
                    writer.WritePropertyName("value");
                    writer.WriteNumberValue(Value.Value);
                }
                else
                {
                    writer.WriteNull("value");
                }
            }
            writer.WriteEndObject();
        }

        internal static IncomeAttributes DeserializeIncomeAttributes(JsonElement element)
        {
            Optional<DateTimeOffset?> updated = default;
            Optional<DateTimeOffset?> created = default;
            Optional<string> description = default;
            Optional<double?> value = default;
            Optional<int?> incomeTypeId = default;
            Optional<string> frequency = default;
            Optional<string> incomeCategory = default;
            Optional<string> incomeType = default;
            Optional<int?> incomeCategoryId = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("updated"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        updated = null;
                        continue;
                    }
                    updated = property.Value.GetDateTimeOffset("O");
                    continue;
                }
                if (property.NameEquals("created"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        created = null;
                        continue;
                    }
                    created = property.Value.GetDateTimeOffset("O");
                    continue;
                }
                if (property.NameEquals("description"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        description = null;
                        continue;
                    }
                    description = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("value"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        value = null;
                        continue;
                    }
                    value = property.Value.GetDouble();
                    continue;
                }
                if (property.NameEquals("incomeTypeId"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        incomeTypeId = null;
                        continue;
                    }
                    incomeTypeId = property.Value.GetInt32();
                    continue;
                }
                if (property.NameEquals("frequency"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        frequency = null;
                        continue;
                    }
                    frequency = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("incomeCategory"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        incomeCategory = null;
                        continue;
                    }
                    incomeCategory = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("incomeType"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        incomeType = null;
                        continue;
                    }
                    incomeType = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("incomeCategoryId"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        incomeCategoryId = null;
                        continue;
                    }
                    incomeCategoryId = property.Value.GetInt32();
                    continue;
                }
            }
            return new IncomeAttributes(Optional.ToNullable(updated), Optional.ToNullable(created), description.Value, Optional.ToNullable(value), Optional.ToNullable(incomeTypeId), frequency.Value, incomeCategory.Value, incomeType.Value, Optional.ToNullable(incomeCategoryId));
        }
    }
}
