// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The LeadOwnership. </summary>
    public partial class LeadOwnership
    {
        /// <summary> Initializes a new instance of LeadOwnership. </summary>
        public LeadOwnership()
        {
        }

        /// <summary> Initializes a new instance of LeadOwnership. </summary>
        /// <param name="lid"></param>
        /// <param name="contact"></param>
        /// <param name="ownershipPercentage"></param>
        internal LeadOwnership(string lid, LeadContact contact, double? ownershipPercentage)
        {
            Lid = lid;
            Contact = contact;
            OwnershipPercentage = ownershipPercentage;
        }

        /// <summary> Gets or sets the lid. </summary>
        public string Lid { get; set; }
        /// <summary> Gets or sets the contact. </summary>
        public LeadContact Contact { get; set; }
        /// <summary> Gets or sets the ownership percentage. </summary>
        public double? OwnershipPercentage { get; set; }
    }
}
