// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace MyCrmSampleClient.MyCrmApi.Models
{
    public partial class LeadContactReference : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("lid");
            writer.WriteStringValue(Lid);
            writer.WriteEndObject();
        }

        internal static LeadContactReference DeserializeLeadContactReference(JsonElement element)
        {
            string lid = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("lid"))
                {
                    lid = property.Value.GetString();
                    continue;
                }
            }
            return new LeadContactReference(lid);
        }
    }
}
