// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The LeadAttributes. </summary>
    public partial class LeadAttributes
    {
        /// <summary> Initializes a new instance of LeadAttributes. </summary>
        public LeadAttributes()
        {
        }

        /// <summary> Initializes a new instance of LeadAttributes. </summary>
        /// <param name="dateOfBirth"></param>
        /// <param name="title"></param>
        /// <param name="firstName"></param>
        /// <param name="preferredName"></param>
        /// <param name="lastName"></param>
        /// <param name="email"></param>
        /// <param name="mobile"></param>
        /// <param name="gender"></param>
        /// <param name="hasMarketingConsent"></param>
        /// <param name="isGuarantor"></param>
        /// <param name="isDependant"></param>
        /// <param name="isPrimary"></param>
        /// <param name="streetAddress"></param>
        /// <param name="suburb"></param>
        /// <param name="state"></param>
        /// <param name="postCode"></param>
        /// <param name="country"></param>
        /// <param name="addressType"></param>
        /// <param name="noteTitle"></param>
        /// <param name="noteDetails"></param>
        /// <param name="utmSource"></param>
        /// <param name="utmMedium"></param>
        /// <param name="utmCampaign"></param>
        /// <param name="utmTerm"></param>
        /// <param name="utmContent"></param>
        /// <param name="sourceSystemUrl"></param>
        /// <param name="customStatusName"></param>
        /// <param name="dealStatus"></param>
        internal LeadAttributes(DateTimeOffset? dateOfBirth, Title? title, string firstName, string preferredName, string lastName, string email, string mobile, Gender? gender, bool? hasMarketingConsent, bool? isGuarantor, bool? isDependant, bool? isPrimary, string streetAddress, string suburb, string state, string postCode, string country, ClientAddressType? addressType, string noteTitle, string noteDetails, string utmSource, string utmMedium, string utmCampaign, string utmTerm, string utmContent, string sourceSystemUrl, string customStatusName, SystemStatus? dealStatus)
        {
            DateOfBirth = dateOfBirth;
            Title = title;
            FirstName = firstName;
            PreferredName = preferredName;
            LastName = lastName;
            Email = email;
            Mobile = mobile;
            Gender = gender;
            HasMarketingConsent = hasMarketingConsent;
            IsGuarantor = isGuarantor;
            IsDependant = isDependant;
            IsPrimary = isPrimary;
            StreetAddress = streetAddress;
            Suburb = suburb;
            State = state;
            PostCode = postCode;
            Country = country;
            AddressType = addressType;
            NoteTitle = noteTitle;
            NoteDetails = noteDetails;
            UtmSource = utmSource;
            UtmMedium = utmMedium;
            UtmCampaign = utmCampaign;
            UtmTerm = utmTerm;
            UtmContent = utmContent;
            SourceSystemUrl = sourceSystemUrl;
            CustomStatusName = customStatusName;
            DealStatus = dealStatus;
        }

        public DateTimeOffset? DateOfBirth { get; set; }
        public Title? Title { get; set; }
        public string FirstName { get; set; }
        public string PreferredName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public Gender? Gender { get; set; }
        public bool? HasMarketingConsent { get; set; }
        public bool? IsGuarantor { get; set; }
        public bool? IsDependant { get; set; }
        public bool? IsPrimary { get; set; }
        public string StreetAddress { get; set; }
        public string Suburb { get; set; }
        public string State { get; set; }
        public string PostCode { get; set; }
        public string Country { get; set; }
        public ClientAddressType? AddressType { get; set; }
        public string NoteTitle { get; set; }
        public string NoteDetails { get; set; }
        public string UtmSource { get; set; }
        public string UtmMedium { get; set; }
        public string UtmCampaign { get; set; }
        public string UtmTerm { get; set; }
        public string UtmContent { get; set; }
        public string SourceSystemUrl { get; set; }
        public string CustomStatusName { get; }
        public SystemStatus? DealStatus { get; set; }
    }
}
