// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using Azure.Core;

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The LeadExpense. </summary>
    public partial class LeadExpense
    {
        /// <summary> Initializes a new instance of LeadExpense. </summary>
        public LeadExpense()
        {
            Ownership = new ChangeTrackingList<LeadOwnership>();
        }

        /// <summary> Initializes a new instance of LeadExpense. </summary>
        /// <param name="lid"></param>
        /// <param name="expenseTypeId"></param>
        /// <param name="description"></param>
        /// <param name="value"></param>
        /// <param name="frequency"></param>
        /// <param name="ownership"></param>
        internal LeadExpense(string lid, int? expenseTypeId, string description, double? value, Frequency? frequency, IList<LeadOwnership> ownership)
        {
            Lid = lid;
            ExpenseTypeId = expenseTypeId;
            Description = description;
            Value = value;
            Frequency = frequency;
            Ownership = ownership;
        }

        /// <summary> Gets or sets the lid. </summary>
        public string Lid { get; set; }
        /// <summary> Gets or sets the expense type id. </summary>
        public int? ExpenseTypeId { get; set; }
        /// <summary> Gets or sets the description. </summary>
        public string Description { get; set; }
        /// <summary> Gets or sets the value. </summary>
        public double? Value { get; set; }
        /// <summary> Gets or sets the frequency. </summary>
        public Frequency? Frequency { get; set; }
        /// <summary> Gets or sets the ownership. </summary>
        public IList<LeadOwnership> Ownership { get; set; }
    }
}
