// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Azure.Core;

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The LeadContact. </summary>
    public partial class LeadContact
    {
        /// <summary> Initializes a new instance of LeadContact. </summary>
        public LeadContact()
        {
            Addresses = new ChangeTrackingList<LeadAddress>();
        }

        /// <summary> Initializes a new instance of LeadContact. </summary>
        /// <param name="lid"></param>
        /// <param name="title"></param>
        /// <param name="firstName"></param>
        /// <param name="preferredName"></param>
        /// <param name="lastName"></param>
        /// <param name="email"></param>
        /// <param name="mobile"></param>
        /// <param name="dateOfBirthAsString"></param>
        /// <param name="dateOfBirth"></param>
        /// <param name="gender"></param>
        /// <param name="hasMarketingConsent"></param>
        /// <param name="isGuarantor"></param>
        /// <param name="isDependant"></param>
        /// <param name="isPrimary"></param>
        /// <param name="addresses"></param>
        internal LeadContact(string lid, Title? title, string firstName, string preferredName, string lastName, string email, string mobile, DateTimeOffset? dateOfBirthAsString, DateTimeOffset? dateOfBirth, Gender? gender, bool? hasMarketingConsent, bool? isGuarantor, bool? isDependant, bool? isPrimary, IList<LeadAddress> addresses)
        {
            Lid = lid;
            Title = title;
            FirstName = firstName;
            PreferredName = preferredName;
            LastName = lastName;
            Email = email;
            Mobile = mobile;
            DateOfBirthAsString = dateOfBirthAsString;
            DateOfBirth = dateOfBirth;
            Gender = gender;
            HasMarketingConsent = hasMarketingConsent;
            IsGuarantor = isGuarantor;
            IsDependant = isDependant;
            IsPrimary = isPrimary;
            Addresses = addresses;
        }

        /// <summary> Gets or sets the lid. </summary>
        public string Lid { get; set; }
        /// <summary> Gets or sets the title. </summary>
        public Title? Title { get; set; }
        /// <summary> Gets or sets the first name. </summary>
        public string FirstName { get; set; }
        /// <summary> Gets or sets the preferred name. </summary>
        public string PreferredName { get; set; }
        /// <summary> Gets or sets the last name. </summary>
        public string LastName { get; set; }
        /// <summary> Gets or sets the email. </summary>
        public string Email { get; set; }
        /// <summary> Gets or sets the mobile. </summary>
        public string Mobile { get; set; }
        /// <summary> Gets or sets the date of birth as string. </summary>
        public DateTimeOffset? DateOfBirthAsString { get; set; }
        /// <summary> Gets or sets the date of birth. </summary>
        public DateTimeOffset? DateOfBirth { get; set; }
        /// <summary> Gets or sets the gender. </summary>
        public Gender? Gender { get; set; }
        /// <summary> Gets or sets the has marketing consent. </summary>
        public bool? HasMarketingConsent { get; set; }
        /// <summary> Gets or sets the is guarantor. </summary>
        public bool? IsGuarantor { get; set; }
        /// <summary> Gets or sets the is dependant. </summary>
        public bool? IsDependant { get; set; }
        /// <summary> Gets or sets the is primary. </summary>
        public bool? IsPrimary { get; set; }
        /// <summary> Gets or sets the addresses. </summary>
        public IList<LeadAddress> Addresses { get; set; }
    }
}
