// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The LeadLinks. </summary>
    public partial class LeadLinks : ResourceLinks
    {
        /// <summary> Initializes a new instance of LeadLinks. </summary>
        internal LeadLinks()
        {
        }

        /// <summary> Initializes a new instance of LeadLinks. </summary>
        /// <param name="self"></param>
        internal LeadLinks(string self) : base(self)
        {
        }
    }
}
