// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The LiabilityLinks. </summary>
    public partial class LiabilityLinks : ResourceLinks
    {
        /// <summary> Initializes a new instance of LiabilityLinks. </summary>
        internal LiabilityLinks()
        {
        }

        /// <summary> Initializes a new instance of LiabilityLinks. </summary>
        /// <param name="self"></param>
        internal LiabilityLinks(string self) : base(self)
        {
        }
    }
}
