// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The LiabilityAttributes. </summary>
    public partial class LiabilityAttributes
    {
        /// <summary> Initializes a new instance of LiabilityAttributes. </summary>
        public LiabilityAttributes()
        {
        }

        /// <summary> Initializes a new instance of LiabilityAttributes. </summary>
        /// <param name="created"></param>
        /// <param name="repayment"></param>
        /// <param name="value"></param>
        /// <param name="limit"></param>
        /// <param name="accountName"></param>
        /// <param name="accountNumber"></param>
        /// <param name="bsb"></param>
        /// <param name="interestTaxDeductible"></param>
        /// <param name="interestRate"></param>
        /// <param name="isAccountDetailsKnown"></param>
        /// <param name="liabilityTypeId"></param>
        /// <param name="loanTerm"></param>
        /// <param name="repaymentFrequency"></param>
        /// <param name="liabilityCategory"></param>
        /// <param name="liabilityCategoryId"></param>
        /// <param name="liabilityType"></param>
        /// <param name="mortgagePriority"></param>
        /// <param name="updated"></param>
        /// <param name="creditorName"></param>
        /// <param name="loanRepaymentType"></param>
        internal LiabilityAttributes(DateTimeOffset? created, double? repayment, double? value, double? limit, string accountName, string accountNumber, string bsb, bool? interestTaxDeductible, double? interestRate, bool? isAccountDetailsKnown, int? liabilityTypeId, int? loanTerm, string repaymentFrequency, string liabilityCategory, int? liabilityCategoryId, string liabilityType, string mortgagePriority, DateTimeOffset? updated, string creditorName, LiabilityAttributesLoanRepaymentType? loanRepaymentType)
        {
            Created = created;
            Repayment = repayment;
            Value = value;
            Limit = limit;
            AccountName = accountName;
            AccountNumber = accountNumber;
            Bsb = bsb;
            InterestTaxDeductible = interestTaxDeductible;
            InterestRate = interestRate;
            IsAccountDetailsKnown = isAccountDetailsKnown;
            LiabilityTypeId = liabilityTypeId;
            LoanTerm = loanTerm;
            RepaymentFrequency = repaymentFrequency;
            LiabilityCategory = liabilityCategory;
            LiabilityCategoryId = liabilityCategoryId;
            LiabilityType = liabilityType;
            MortgagePriority = mortgagePriority;
            Updated = updated;
            CreditorName = creditorName;
            LoanRepaymentType = loanRepaymentType;
        }

        /// <summary> Gets the created. </summary>
        public DateTimeOffset? Created { get; }
        /// <summary> Gets or sets the repayment. </summary>
        public double? Repayment { get; set; }
        /// <summary> Gets or sets the value. </summary>
        public double? Value { get; set; }
        /// <summary> Gets or sets the limit. </summary>
        public double? Limit { get; set; }
        /// <summary> Gets or sets the account name. </summary>
        public string AccountName { get; set; }
        /// <summary> Gets or sets the account number. </summary>
        public string AccountNumber { get; set; }
        /// <summary> Gets or sets the bsb. </summary>
        public string Bsb { get; set; }
        /// <summary> Gets or sets the interest tax deductible. </summary>
        public bool? InterestTaxDeductible { get; set; }
        /// <summary> Gets or sets the interest rate. </summary>
        public double? InterestRate { get; set; }
        /// <summary> Gets or sets the is account details known. </summary>
        public bool? IsAccountDetailsKnown { get; set; }
        /// <summary> Gets the liability type id. </summary>
        public int? LiabilityTypeId { get; }
        /// <summary> Gets or sets the loan term. </summary>
        public int? LoanTerm { get; set; }
        /// <summary> Gets the repayment frequency. </summary>
        public string RepaymentFrequency { get; }
        /// <summary> Gets the liability category. </summary>
        public string LiabilityCategory { get; }
        /// <summary> Gets the liability category id. </summary>
        public int? LiabilityCategoryId { get; }
        /// <summary> Gets the liability type. </summary>
        public string LiabilityType { get; }
        /// <summary> Gets the mortgage priority. </summary>
        public string MortgagePriority { get; }
        /// <summary> Gets the updated. </summary>
        public DateTimeOffset? Updated { get; }
        /// <summary> Gets the creditor name. </summary>
        public string CreditorName { get; }
        /// <summary> Gets the loan repayment type. </summary>
        public LiabilityAttributesLoanRepaymentType? LoanRepaymentType { get; }
    }
}
