// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using Azure.Core;

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The LiabilitySubType. </summary>
    public partial class LiabilitySubType : IncludedResource
    {
        /// <summary> Initializes a new instance of LiabilitySubType. </summary>
        public LiabilitySubType()
        {
            Meta = new ChangeTrackingDictionary<string, object>();
            Type = "liability-sub-types";
        }

        /// <summary> Initializes a new instance of LiabilitySubType. </summary>
        /// <param name="type"></param>
        /// <param name="id"></param>
        /// <param name="attributes"></param>
        /// <param name="relationships"> Any object. </param>
        /// <param name="links"></param>
        /// <param name="meta"> Dictionary of &lt;any&gt;. </param>
        internal LiabilitySubType(string type, string id, LiabilitySubTypeAttributes attributes, object relationships, LiabilitySubTypeLinks links, IReadOnlyDictionary<string, object> meta) : base(type, id)
        {
            Attributes = attributes;
            Relationships = relationships;
            Links = links;
            Meta = meta;
            Type = type ?? "liability-sub-types";
        }

        /// <summary> Gets or sets the attributes. </summary>
        public LiabilitySubTypeAttributes Attributes { get; set; }
        /// <summary> Any object. </summary>
        public object Relationships { get; set; }
        /// <summary> Gets the links. </summary>
        public LiabilitySubTypeLinks Links { get; }
        /// <summary> Dictionary of &lt;any&gt;. </summary>
        public IReadOnlyDictionary<string, object> Meta { get; }
    }
}
