// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The LoanStructureImportantDateTypes. </summary>
    internal readonly partial struct LoanStructureImportantDateTypes : IEquatable<LoanStructureImportantDateTypes>
    {
        private readonly string _value;

        /// <summary> Initializes a new instance of <see cref="LoanStructureImportantDateTypes"/>. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public LoanStructureImportantDateTypes(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string InterestOnlyValue = "InterestOnly";
        private const string RepaymentHolidayValue = "RepaymentHoliday";

        /// <summary> InterestOnly. </summary>
        public static LoanStructureImportantDateTypes InterestOnly { get; } = new LoanStructureImportantDateTypes(InterestOnlyValue);
        /// <summary> RepaymentHoliday. </summary>
        public static LoanStructureImportantDateTypes RepaymentHoliday { get; } = new LoanStructureImportantDateTypes(RepaymentHolidayValue);
        /// <summary> Determines if two <see cref="LoanStructureImportantDateTypes"/> values are the same. </summary>
        public static bool operator ==(LoanStructureImportantDateTypes left, LoanStructureImportantDateTypes right) => left.Equals(right);
        /// <summary> Determines if two <see cref="LoanStructureImportantDateTypes"/> values are not the same. </summary>
        public static bool operator !=(LoanStructureImportantDateTypes left, LoanStructureImportantDateTypes right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="LoanStructureImportantDateTypes"/>. </summary>
        public static implicit operator LoanStructureImportantDateTypes(string value) => new LoanStructureImportantDateTypes(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is LoanStructureImportantDateTypes other && Equals(other);
        /// <inheritdoc />
        public bool Equals(LoanStructureImportantDateTypes other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
