// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The Paths14966DnJsonapiDealParticipantsIdRelationshipnameGetResponses200ContentApplicationVndApiJsonSchema. </summary>
    public partial class Paths14966DnJsonapiDealParticipantsIdRelationshipnameGetResponses200ContentApplicationVndApiJsonSchema
    {
        /// <summary> Initializes a new instance of Paths14966DnJsonapiDealParticipantsIdRelationshipnameGetResponses200ContentApplicationVndApiJsonSchema. </summary>
        internal Paths14966DnJsonapiDealParticipantsIdRelationshipnameGetResponses200ContentApplicationVndApiJsonSchema()
        {
        }
    }
}
