// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;

namespace MyCrmSampleClient.MyCrmApi.Models
{
    public partial class Paths1Ugotj3JsonapiDealExternalReferencesIdRelationshipnameGetResponses200ContentApplicationVndApiJsonSchema
    {
        internal static Paths1Ugotj3JsonapiDealExternalReferencesIdRelationshipnameGetResponses200ContentApplicationVndApiJsonSchema DeserializePaths1Ugotj3JsonapiDealExternalReferencesIdRelationshipnameGetResponses200ContentApplicationVndApiJsonSchema(JsonElement element)
        {
            foreach (var property in element.EnumerateObject())
            {
            }
            return new Paths1Ugotj3JsonapiDealExternalReferencesIdRelationshipnameGetResponses200ContentApplicationVndApiJsonSchema();
        }
    }
}
