// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;

namespace MyCrmSampleClient.MyCrmApi.Models
{
    public partial class Paths1B1C1DiJsonapiContactExternalReferencesIdRelationshipnameGetResponses200ContentApplicationVndApiJsonSchema
    {
        internal static Paths1B1C1DiJsonapiContactExternalReferencesIdRelationshipnameGetResponses200ContentApplicationVndApiJsonSchema DeserializePaths1B1C1DiJsonapiContactExternalReferencesIdRelationshipnameGetResponses200ContentApplicationVndApiJsonSchema(JsonElement element)
        {
            foreach (var property in element.EnumerateObject())
            {
            }
            return new Paths1B1C1DiJsonapiContactExternalReferencesIdRelationshipnameGetResponses200ContentApplicationVndApiJsonSchema();
        }
    }
}
