// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The ResourceObjectLinks. </summary>
    public partial class ResourceObjectLinks : ResourceLinks
    {
        /// <summary> Initializes a new instance of ResourceObjectLinks. </summary>
        internal ResourceObjectLinks()
        {
        }

        /// <summary> Initializes a new instance of ResourceObjectLinks. </summary>
        /// <param name="self"></param>
        internal ResourceObjectLinks(string self) : base(self)
        {
        }
    }
}
