// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using Azure.Core;

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The Split. </summary>
    public partial class Split
    {
        /// <summary> Initializes a new instance of Split. </summary>
        internal Split()
        {
            Dates = new ChangeTrackingList<SplitDates>();
        }

        /// <summary> Initializes a new instance of Split. </summary>
        /// <param name="loanTermYears"></param>
        /// <param name="rateType"></param>
        /// <param name="loanStructureType"></param>
        /// <param name="amount"></param>
        /// <param name="interestRate"></param>
        /// <param name="rateTypePeriodMonths"></param>
        /// <param name="paymentAmount"></param>
        /// <param name="dates"></param>
        internal Split(double? loanTermYears, string rateType, LoanStructureType? loanStructureType, double? amount, double? interestRate, int? rateTypePeriodMonths, double? paymentAmount, IReadOnlyList<SplitDates> dates)
        {
            LoanTermYears = loanTermYears;
            RateType = rateType;
            LoanStructureType = loanStructureType;
            Amount = amount;
            InterestRate = interestRate;
            RateTypePeriodMonths = rateTypePeriodMonths;
            PaymentAmount = paymentAmount;
            Dates = dates;
        }

        public double? LoanTermYears { get; }
        public string RateType { get; }
        public LoanStructureType? LoanStructureType { get; }
        public double? Amount { get; }
        public double? InterestRate { get; }
        public int? RateTypePeriodMonths { get; }
        public double? PaymentAmount { get; }
        public IReadOnlyList<SplitDates> Dates { get; }
    }
}
