// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace MyCrmSampleClient.MyCrmApi.Models
{
    /// <summary> The TopLevelLinks. </summary>
    public partial class TopLevelLinks
    {
        /// <summary> Initializes a new instance of TopLevelLinks. </summary>
        internal TopLevelLinks()
        {
        }

        /// <summary> Initializes a new instance of TopLevelLinks. </summary>
        /// <param name="self"></param>
        /// <param name="related"></param>
        /// <param name="describedBy"></param>
        /// <param name="first"></param>
        /// <param name="last"></param>
        /// <param name="prev"></param>
        /// <param name="next"></param>
        internal TopLevelLinks(string self, string related, string describedBy, string first, string last, string prev, string next)
        {
            Self = self;
            Related = related;
            DescribedBy = describedBy;
            First = first;
            Last = last;
            Prev = prev;
            Next = next;
        }

        public string Self { get; }
        public string Related { get; }
        public string DescribedBy { get; }
        public string First { get; }
        public string Last { get; }
        public string Prev { get; }
        public string Next { get; }
    }
}
